const ShopActionTypes = {
    PENDING_COLLECTIONS: 'PENDING_COLLECTIONS',
    SUCCESS_COLLECTIONS: 'SUCCESS_COLLECTIONS',
    FAILURE_COLLECTIONS: 'FAILURE_COLLECTIONS'
}

export default ShopActionTypes;